/**
 * WASM Layer Types for LEP-1 Operations
 * 
 * This module defines the core types used by the WASM layer for RaptorQ
 * layout generation and LEP-1 (Lumera Enhancement Proposal 1) operations.
 */

/**
 * RaptorQ layout generated by rq-wasm for a single block.
 * 
 * This layout contains the parameters needed for RaptorQ encoding/decoding,
 * including the transfer length, symbol size, and block structure.
 * 
 * @remarks
 * The layout is deterministic based on the input file bytes and is used
 * to derive layout IDs according to LEP-1 specifications.
 */
export interface Layout {
  /**
   * Total transfer length in bytes
   */
  transfer_length: number;
  
  /**
   * Size of each symbol in bytes
   */
  symbol_size: number;
  
  /**
   * Number of source blocks
   */
  num_source_blocks: number;
  
  /**
   * Number of sub-blocks
   */
  num_sub_blocks: number;
  
  /**
   * Symbol alignment in bytes
   */
  symbol_alignment: number;
  
  /**
   * Source block parameters for each block
   */
  source_blocks: SourceBlock[];
}

/**
 * Parameters for a single source block in a RaptorQ layout.
 */
export interface SourceBlock {
  /**
   * Number of source symbols in this block
   */
  source_symbols: number;
  
  /**
   * Number of sub-symbols per symbol
   */
  sub_symbols: number;
  
  /**
   * Size of each sub-symbol in bytes
   */
  sub_symbol_size: number;
}

/**
 * Index file structure for LEP-1 Cascade uploads.
 * 
 * The index file contains metadata about the RaptorQ layout and is signed
 * by the uploader to ensure data integrity. It includes 50 derived layout IDs
 * and a cryptographic signature over the layout data.
 * 
 * @remarks
 * This structure must be serialized deterministically (canonical JSON) when
 * computing signatures to ensure cross-platform compatibility.
 */
export interface IndexFile {
  /**
   * LEP-1 protocol version
   * 
   * @remarks
   * Currently fixed at 1 for LEP-1 specification
   */
  version: number;
  
  /**
   * Array of 50 derived layout IDs.
   * 
   * @remarks
   * Derived from (rq_ids_ic + i) % rq_ids_max for i in [0, 50),
   * where rq_ids_ic is the initial counter from blockchain params
   * and rq_ids_max is the maximum layout ID from blockchain params.
   */
  layout_ids: number[];
  
  /**
   * Cryptographic signature over the layout data.
   * 
   * @remarks
   * Generated by signing the canonical JSON bytes of the layout
   * using ADR-036 signArbitrary with the uploader's wallet.
   * Stored as Base64-encoded bytes.
   */
  layout_signature: Uint8Array;
}