/**
 * Blockchain client facade for the Lumera blockchain.
 *
 * This module provides the main entry point for blockchain operations, composing
 * transaction and query clients into a unified interface. It orchestrates CosmJS
 * for transaction operations and uses RPC-based query clients generated by Telescope
 * for type-safe module queries.
 *
 * @module blockchain/client
 */

import { SigningStargateClient, GasPrice, QueryClient, createProtobufRpcClient } from "@cosmjs/stargate";
import type { OfflineSigner } from "@cosmjs/proto-signing";
import { connectComet } from "@cosmjs/tendermint-rpc";
import type { CometClient } from "@cosmjs/tendermint-rpc";
import type {
  TxClient,
  ActionQuery,
  SupernodeQuery,
  BlockchainClient,
  ActionParams,
  ActionRecord,
  SupernodeParams,
  SupernodeRecord
} from "./interfaces";
import { CosmjsTxClient } from "./cosmjs";
import { createRegistry, createAminoTypes } from "./registry";
import { QueryClientImpl as ActionQueryClient } from "../codegen/lumera/action/query.rpc.Query";
import { QueryClientImpl as SupernodeQueryClient } from "../codegen/lumera/supernode/query.rpc.Query";
import { base64FromBytes } from "../codegen/helpers";
import type { SuperNode } from "../codegen/lumera/supernode/super_node";
import type { SuperNodeStateRecord } from "../codegen/lumera/supernode/supernode_state";
import type { Evidence } from "../codegen/lumera/supernode/evidence";
import type { IPAddressHistory } from "../codegen/lumera/supernode/ip_address_history";
import type { SupernodeAccountHistory } from "../codegen/lumera/supernode/supernode_account_history";

/**
 * RPC-based Action query client adapter.
 *
 * Wraps the generated Telescope RPC query client and adapts it to the ActionQuery interface.
 * Provides backward compatibility while using the type-safe generated clients internally.
 */
class RpcActionQuery implements ActionQuery {
  constructor(private readonly client: ActionQueryClient) {}

  async getParams(): Promise<ActionParams> {
    const response = await this.client.params({});
    
    const params = response.params;
    return {
      fee_base: params?.baseActionFee?.amount ?? "0",
      fee_per_kb: params?.feePerKbyte?.amount ?? "0",
      max_raptor_q_symbols: params?.maxRaptorQSymbols?.toString() ?? "0",
    };
  }

  async getAction(actionId: string): Promise<ActionRecord> {
    const response = await this.client.getAction({ actionID: actionId });

    if (!response.action) {
      throw new Error(`Action not found: ${actionId}`);
    }

    const action = response.action;

    // Decode the metadata bytes as JSON
    const decodedMetadata = JSON.parse(new TextDecoder().decode(action.metadata));

    return {
      creator: action.creator,
      actionID: action.actionID,
      actionType: action.actionType as any,
      metadata: decodedMetadata,
      price: action.price,
      expirationTime: Number(action.expirationTime),
      state: action.state as any,
      blockHeight: Number(action.blockHeight),
      superNodes: action.superNodes,
    };
  }

  async getActionFee(dataSize: number): Promise<{ amount: string }> {
    const response = await this.client.getActionFee({ dataSize: dataSize.toString() });
    
    return {
      amount: response.amount ?? "0",
    };
  }
}

/**
 * RPC-based Supernode query client adapter.
 *
 * Wraps the generated Telescope RPC query client and adapts it to the SupernodeQuery interface.
 * Provides backward compatibility while using the type-safe generated clients internally.
 */
/**
 * Helper to convert generated SuperNode to SupernodeRecord interface.
 */
function convertSupernodeRecord(sn: SuperNode): SupernodeRecord {
  return {
    validatorAddress: sn.validatorAddress,
    supernodeAccount: sn.supernodeAccount,
    p2pPort: sn.p2pPort,
    states: (sn.states || []).map((s: SuperNodeStateRecord) => ({
      state: s.state as any,
      height: Number(s.height),
    })),
    evidence: (sn.evidence || []).map((e: Evidence) => ({
      reporterAddress: e.reporterAddress,
      validatorAddress: e.validatorAddress,
      actionId: e.actionId,
      evidenceType: e.evidenceType,
      description: e.description,
      severity: Number(e.severity),
      height: Number(e.height),
    })),
    prevIpAddresses: (sn.prevIpAddresses || []).map((ip: IPAddressHistory) => ({
      address: ip.address,
      height: Number(ip.height),
    })),
    note: sn.note,
    metrics: {
      metrics: Object.fromEntries(
        Object.entries(sn.metrics?.metrics || {}).map(([key, value]) => [
          key,
          parseFloat(value?.toString() ?? "0"),
        ])
      ),
      reportCount: Number(sn.metrics?.reportCount ?? 0),
      height: Number(sn.metrics?.height ?? 0),
    },
    prevSupernodeAccounts: (sn.prevSupernodeAccounts || []).map((acc: SupernodeAccountHistory) => ({
      account: acc.account,
      height: Number(acc.height),
    })),
  };
}

class RpcSupernodeQuery implements SupernodeQuery {
  constructor(private readonly client: SupernodeQueryClient) {}

  async getParams(): Promise<SupernodeParams> {
    const response = await this.client.params({});
    
    // Return the params object as-is, since SupernodeParams accepts any fields
    return response.params ? { ...response.params } : {};
  }

  async getSupernode(validatorAddress: string): Promise<SupernodeRecord> {
    const response = await this.client.getSuperNode({ validatorAddress });

    if (!response.supernode) {
      throw new Error(`Supernode not found: ${validatorAddress}`);
    }

    return convertSupernodeRecord(response.supernode);
  }

  async getSupernodeByAddress(supernodeAddress: string): Promise<SupernodeRecord> {
    const response = await this.client.getSuperNodeBySuperNodeAddress({
      supernodeAddress,
    });

    if (!response.supernode) {
      throw new Error(`Supernode not found: ${supernodeAddress}`);
    }

    return convertSupernodeRecord(response.supernode);
  }

  async listSupernodes(): Promise<SupernodeRecord[]> {
    const response = await this.client.listSuperNodes({});

    return (response.supernodes || []).map(convertSupernodeRecord);
  }
}

/**
 * Helper function to create RPC query clients from an RPC endpoint.
 *
 * Creates a direct CometClient connection and instantiates the generated
 * query clients for the Lumera modules.
 *
 * @param rpcEndpoint - The Tendermint RPC endpoint URL
 * @returns Promise resolving to object containing instantiated query clients
 */
async function createQueryClients(rpcEndpoint: string) {
  // Create a direct CometClient connection using connectComet
  const tmClient = await connectComet(rpcEndpoint);
  
  // Create a QueryClient wrapper
  const queryClient = new QueryClient(tmClient);
  
  // Create protobuf RPC client
  const rpc = createProtobufRpcClient(queryClient);
  
  // Instantiate generated query clients
  return {
    action: new ActionQueryClient(rpc),
    supernode: new SupernodeQueryClient(rpc),
  };
}

/**
 * Implementation of BlockchainClient using CosmJS and RPC query clients.
 *
 * This class combines a CosmJS transaction client with RPC-based query clients
 * to provide a complete blockchain interaction interface. It serves as the facade
 * for all blockchain operations.
 */
export class CosmjsRestBlockchainClient implements BlockchainClient {
  /**
   * Create a new blockchain client instance.
   * 
   * @param Tx - Transaction client for signing and broadcasting
   * @param Action - Action module query client
   * @param Supernode - Supernode module query client
   * @param chainId - Blockchain network identifier
   * @param bech32Address - Signer's bech32 address
   */
  constructor(
    public readonly Tx: TxClient,
    public readonly Action: ActionQuery,
    public readonly Supernode: SupernodeQuery,
    private readonly chainId: string,
    private readonly bech32Address: string,
  ) {}

  /**
   * Get the chain ID.
   * 
   * @returns Chain ID (e.g., "lumera-testnet-2")
   */
  async getChainId(): Promise<string> {
    return this.chainId;
  }

  /**
   * Get the signer's address.
   * 
   * @returns Bech32 address of the account associated with this client
   */
  async getAddress(): Promise<string> {
    return this.bech32Address;
  }
}

/**
 * Configuration options for creating a blockchain client.
 */
export interface BlockchainClientOptions {
  /** Tendermint RPC URL for transaction and query operations (e.g., "https://rpc.testnet.lumera.io") */
  rpcUrl: string;

  /** LCD REST API URL for transaction broadcasting fallback (e.g., "https://lcd.testnet.lumera.io") */
  lcdUrl: string;

  /** Blockchain network identifier (e.g., "lumera-testnet-2") */
  chainId: string;

  /** CosmJS offline signer (wallet) for transaction signing */
  signer: OfflineSigner;

  /** Bech32 address of the signing account */
  address: string;

  /** Gas price string (e.g., "0.025ulume"). If not provided, defaults will be used. */
  gasPrice?: string;
}

/**
 * Create a new blockchain client.
 *
 * This factory function initializes a complete blockchain client with transaction
 * and query capabilities. It connects to the Tendermint RPC endpoint for both
 * transactions and queries, using Telescope-generated type-safe query clients.
 * The LCD REST API is used as a fallback for transaction broadcasting.
 *
 * @param opts - Configuration options for the client
 * @returns Promise resolving to a configured BlockchainClient
 * @throws {Error} If connection to RPC fails or configuration is invalid
 *
 * @example
 * ```typescript
 * import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
 * import { makeBlockchainClient, lumera } from "@lumera/sdk-js";
 *
 * // Create a wallet
 * const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic, {
 *   prefix: "lumera"
 * });
 * const [account] = await wallet.getAccounts();
 *
 * // Create the blockchain client
 * const client = await makeBlockchainClient({
 *   rpcUrl: "https://rpc.testnet.lumera.io",
 *   lcdUrl: "https://lcd.testnet.lumera.io",
 *   chainId: "lumera-testnet-2",
 *   signer: wallet,
 *   address: account.address,
 *   gasPrice: "0.025ulume"
 * });
 *
 * // Type-safe RPC queries using generated clients
 * const params = await client.Action.getParams();
 * console.log("Max RaptorQ Symbols:", params.max_raptor_q_symbols);
 *
 * // Build messages using generated MessageComposer
 * const msg = lumera.action.MessageComposer.withTypeUrl.requestAction({
 *   creator: account.address,
 *   actionType: "cascade",
 *   metadata: JSON.stringify(metadata),
 *   price: "100000",
 *   expirationTime: "1735689600"
 * });
 *
 * // Simulate and broadcast a transaction
 * const gas = await client.Tx.simulate(account.address, [msg]);
 * const result = await client.Tx.signAndBroadcast(
 *   account.address,
 *   [msg],
 *   { amount: [{ denom: "ulume", amount: "5000" }], gas: gas.toString() }
 * );
 * console.log("TX Hash:", result.txHash);
 * ```
 */
export async function makeBlockchainClient(
  opts: BlockchainClientOptions
): Promise<BlockchainClient> {
  // Create registry and amino types with Lumera-specific message types
  const registry = createRegistry();
  const aminoTypes = createAminoTypes();
  
  // Connect to Tendermint RPC via CosmJS SigningStargateClient
  const signingClient = await SigningStargateClient.connectWithSigner(
    opts.rpcUrl,
    opts.signer,
    {
      registry,
      aminoTypes,
      gasPrice: opts.gasPrice ? GasPrice.fromString(opts.gasPrice) : undefined,
    }
  );

  // Create transaction client with REST fallback support
  const txClient = new CosmjsTxClient(signingClient, {
    lcdBaseUrl: opts.lcdUrl,
    gasMultiplier: 1.5,
  });

  // Create RPC query clients using a direct CometClient connection
  const rpcClients = await createQueryClients(opts.rpcUrl);
  
  // Wrap generated clients with adapter classes for backward compatibility
  const actionQuery = new RpcActionQuery(rpcClients.action);
  const supernodeQuery = new RpcSupernodeQuery(rpcClients.supernode);

  // Compose into the unified blockchain client facade
  return new CosmjsRestBlockchainClient(
    txClient,
    actionQuery,
    supernodeQuery,
    opts.chainId,
    opts.address
  );
}

// Export classes and types for direct use if needed
export { CosmjsTxClient } from "./cosmjs";
export { broadcastTx } from "./rest";
export * from "./interfaces";
export * from "./messages";
export * from "./registry";