/**
 * Blockchain client facade for the Lumera blockchain.
 *
 * This module provides the main entry point for blockchain operations, composing
 * transaction and query clients into a unified interface. It orchestrates CosmJS
 * for transaction operations and uses RPC-based query clients generated by Telescope
 * for type-safe module queries.
 *
 * @module blockchain/client
 */

import { SigningStargateClient, GasPrice, QueryClient, createProtobufRpcClient } from "@cosmjs/stargate";
import type { OfflineSigner } from "@cosmjs/proto-signing";
import { connectComet } from "@cosmjs/tendermint-rpc";
import type { CometClient } from "@cosmjs/tendermint-rpc";
import type {
  TxClient,
  ActionQuery,
  SupernodeQuery,
  BlockchainClient,
  ActionParams,
  ActionRecord,
  SupernodeParams,
  SuperNode
} from "./interfaces";
import { CosmjsTxClient } from "./cosmjs";
import { QueryClientImpl as ActionQueryClient } from "../codegen/lumera/action/v1/query.rpc.Query";
import { QueryClientImpl as SupernodeQueryClient } from "../codegen/lumera/supernode/v1/query.rpc.Query";
import { getSigningLumeraClientOptions } from "../codegen/lumera/client";
import { safeJsonStringify } from "../internal/encoding";

/**
 * RPC-based Action query client adapter.
 *
 * Wraps the generated Telescope RPC query client and adapts it to the ActionQuery interface.
 * Provides backward compatibility while using the type-safe generated clients internally.
 */
class RpcActionQuery implements ActionQuery {
  constructor(private readonly client: ActionQueryClient) {}

  async getParams(): Promise<ActionParams> {
    const response = await this.client.params({});
    
    const params = response.params;
    return {
      fee_base: params?.baseActionFee?.amount ?? "0",
      fee_per_kb: params?.feePerKbyte?.amount ?? "0",
      max_raptor_q_symbols: params?.maxRaptorQSymbols?.toString() ?? "0",
    };
  }

  async getAction(actionId: string): Promise<ActionRecord> {
    const response = await this.client.getAction({ actionID: actionId });

    if (!response.action) {
      throw new Error(`Action not found: ${actionId}`);
    }

    const action = response.action;

    // Decode the metadata bytes as JSON
    const decodedMetadata = JSON.parse(new TextDecoder().decode(action.metadata));

    const result = {
      creator: action.creator,
      actionID: action.actionID,
      actionType: action.actionType as any,
      metadata: decodedMetadata,
      price: action.price,
      expirationTime: Number(action.expirationTime),
      state: action.state as any,
      blockHeight: Number(action.blockHeight),
      superNodes: action.superNodes,
    };

    // Convert any BigInt values to strings to prevent precision loss
    return JSON.parse(safeJsonStringify(result));
  }

  async getActionFee(dataSize: number): Promise<{ amount: string }> {
    const response = await this.client.getActionFee({ dataSize: dataSize.toString() });
    
    return {
      amount: response.amount ?? "0",
    };
  }
}

/**
 * RPC-based Supernode query client adapter.
 *
 * Wraps the generated Telescope RPC query client and adapts it to the SupernodeQuery interface.
 * Now returns generated SuperNode types directly without conversion.
 */

class RpcSupernodeQuery implements SupernodeQuery {
  constructor(private readonly client: SupernodeQueryClient) {}

  async getParams(): Promise<SupernodeParams> {
    const response = await this.client.params({});
    
    // Return the params object as-is, since SupernodeParams accepts any fields
    return response.params ? { ...response.params } : {};
  }

  async getSupernode(validatorAddress: string): Promise<SuperNode> {
    const response = await this.client.getSuperNode({ validatorAddress });

    if (!response.supernode) {
      throw new Error(`Supernode not found: ${validatorAddress}`);
    }

    return response.supernode;
  }

  async getSupernodeByAddress(supernodeAddress: string): Promise<SuperNode> {
    const response = await this.client.getSuperNodeBySuperNodeAddress({
      supernodeAddress,
    });

    if (!response.supernode) {
      throw new Error(`Supernode not found: ${supernodeAddress}`);
    }

    // Convert any BigInt values to strings to prevent precision loss
    return JSON.parse(safeJsonStringify(response.supernode));
  }

  async listSupernodes(): Promise<SuperNode[]> {
    const response = await this.client.listSuperNodes({});

    const supernodes = response.supernodes || [];
    
    // Convert any BigInt values to strings to prevent precision loss
    return JSON.parse(safeJsonStringify(supernodes));
  }
}

/**
 * Helper function to create RPC query clients from an RPC endpoint.
 *
 * Creates a direct CometClient connection and instantiates the generated
 * query clients for the Lumera modules.
 *
 * @param rpcEndpoint - The Tendermint RPC endpoint URL
 * @returns Promise resolving to object containing instantiated query clients
 */
async function createQueryClients(rpcEndpoint: string) {
  // Create a direct CometClient connection using connectComet
  const tmClient = await connectComet(rpcEndpoint);
  
  // Create a QueryClient wrapper
  const queryClient = new QueryClient(tmClient);
  
  // Create protobuf RPC client
  const rpc = createProtobufRpcClient(queryClient);
  
  // Instantiate generated query clients
  return {
    action: new ActionQueryClient(rpc),
    supernode: new SupernodeQueryClient(rpc),
  };
}

/**
 * Implementation of BlockchainClient using CosmJS for transactions and RPC for queries.
 *
 * This class provides a complete RPC-based blockchain interaction interface, using
 * CosmJS for transaction signing and broadcasting, and Telescope-generated RPC clients
 * for type-safe module queries. It serves as the facade for all blockchain operations.
 */
export class CosmjsRpcBlockchainClient implements BlockchainClient {
  /**
   * Create a new blockchain client instance.
   * 
   * @param Tx - Transaction client for signing and broadcasting
   * @param Action - Action module query client
   * @param Supernode - Supernode module query client
   * @param chainId - Blockchain network identifier
   * @param bech32Address - Signer's bech32 address
   */
  constructor(
    public readonly Tx: TxClient,
    public readonly Action: ActionQuery,
    public readonly Supernode: SupernodeQuery,
    private readonly chainId: string,
    private readonly bech32Address: string,
  ) {}

  /**
   * Get the chain ID.
   * 
   * @returns Chain ID (e.g., "lumera-testnet-2")
   */
  async getChainId(): Promise<string> {
    return this.chainId;
  }

  /**
   * Get the signer's address.
   * 
   * @returns Bech32 address of the account associated with this client
   */
  async getAddress(): Promise<string> {
    return this.bech32Address;
  }
}

/**
 * Configuration options for creating a blockchain client.
 */
export interface BlockchainClientOptions {
  /** Tendermint RPC URL for transaction and query operations (e.g., "https://rpc.testnet.lumera.io") */
  rpcUrl: string;

  /** LCD REST API URL (optional, no longer used for transaction broadcasting) */
  lcdUrl?: string;

  /** Blockchain network identifier (e.g., "lumera-testnet-2") */
  chainId: string;

  /** CosmJS offline signer (wallet) for transaction signing */
  signer: OfflineSigner;

  /** Bech32 address of the signing account */
  address: string;

  /** Gas price string (e.g., "0.025ulume"). If not provided, defaults will be used. */
  gasPrice?: string;
}

/**
 * Create a new RPC-based blockchain client.
 *
 * This factory function initializes a complete blockchain client using RPC for all
 * operations. It uses CosmJS for transaction signing and broadcasting via RPC, and
 * Telescope-generated type-safe RPC clients for all module queries.
 *
 * @param opts - Configuration options for the client
 * @returns Promise resolving to a configured BlockchainClient
 * @throws {Error} If connection to RPC fails or configuration is invalid
 *
 * @example
 * ```typescript
 * import { DirectSecp256k1HdWallet } from "@cosmjs/proto-signing";
 * import { makeBlockchainClient, lumera } from "@lumera/sdk-js";
 *
 * // Create a wallet
 * const wallet = await DirectSecp256k1HdWallet.fromMnemonic(mnemonic, {
 *   prefix: "lumera"
 * });
 * const [account] = await wallet.getAccounts();
 *
 * // Create the RPC-based blockchain client
 * const client = await makeBlockchainClient({
 *   rpcUrl: "https://rpc.testnet.lumera.io",
 *   chainId: "lumera-testnet-2",
 *   signer: wallet,
 *   address: account.address,
 *   gasPrice: "0.025ulume"
 * });
 *
 * // Type-safe RPC queries using generated clients
 * const params = await client.Action.getParams();
 * console.log("Max RaptorQ Symbols:", params.max_raptor_q_symbols);
 *
 * // Build messages using generated MessageComposer
 * const msg = lumera.action.v1.MessageComposer.withTypeUrl.requestAction({
 *   creator: account.address,
 *   actionType: "cascade",
 *   metadata: JSON.stringify(metadata),
 *   price: "100000",
 *   expirationTime: "1735689600"
 * });
 *
 * // Simulate and broadcast a transaction via RPC
 * const gas = await client.Tx.simulate(account.address, [msg]);
 * const result = await client.Tx.signAndBroadcast(
 *   account.address,
 *   [msg],
 *   { amount: [{ denom: "ulume", amount: "5000" }], gas: gas.toString() }
 * );
 * console.log("TX Hash:", result.txHash);
 * ```
 */
export async function makeBlockchainClient(
  opts: BlockchainClientOptions
): Promise<BlockchainClient> {
  // Create registry and amino types with Lumera-specific message types using generated helper
  const { registry, aminoTypes } = getSigningLumeraClientOptions();
  
  console.debug("Created registry and amino types from generated code");
  console.debug("Connecting to RPC endpoint:", opts.rpcUrl);

  // Connect to Tendermint RPC via CosmJS SigningStargateClient
  const signingClient = await SigningStargateClient.connectWithSigner(
    opts.rpcUrl,
    opts.signer,
    {
      registry,
      aminoTypes,
      gasPrice: opts.gasPrice ? GasPrice.fromString(opts.gasPrice) : undefined,
    }
  );

  console.debug("Connected to RPC and created SigningStargateClient");

  // Verify chain ID matches configuration
  const actualChainId = await signingClient.getChainId();
  if (actualChainId !== opts.chainId) {
    throw new Error(`Chain ID mismatch: configured ${opts.chainId}, but RPC reports ${actualChainId}`);
  }
  console.debug("Created transaction client");

  // Create transaction client
  const txClient = new CosmjsTxClient(signingClient, {
    gasMultiplier: 1.5,
  });

  console.debug("Created transaction client");
  console.debug("Creating RPC query clients");

  // Create RPC query clients using a direct CometClient connection
  const rpcClients = await createQueryClients(opts.rpcUrl);
  
  console.debug("Created RPC query clients");
  console.debug("Wrapping query clients with adapters");

  // Wrap generated clients with adapter classes for backward compatibility
  const actionQuery = new RpcActionQuery(rpcClients.action);
  const supernodeQuery = new RpcSupernodeQuery(rpcClients.supernode);

  console.debug("Wrapped query clients with adapters");
  console.debug("Blockchain client creation complete");

  // Compose into the unified blockchain client facade
  return new CosmjsRpcBlockchainClient(
    txClient,
    actionQuery,
    supernodeQuery,
    opts.chainId,
    opts.address
  );
}

// Export classes and types for direct use if needed
export { CosmjsTxClient } from "./cosmjs";
export * from "./interfaces";
export * from "./messages";
export * from "./registry";